pl:
  krystianzybala:
    proxy:
      baseUrl: http://localhost
      endpoint: /pjp-api/rest/station/sensors/14
    stubs:
      ext: .json
      target: target/stubs
    wiremock:
      record:
        target: http://api.gios.gov.pl